name             "sqlite3"
maintainer       "amitizle"
maintainer_email "amit.goldberg@gmail.com"
license          "MIT"
description      "SQLite3"
long_description "SQLite3"
version          "0.0.1"
